uniconf:
  keys:
    include: from
    sources: sources
    params: params
    jobs: jobs
  dirs:
    sources: scenarios
  include:
    prefix: .params.

processors:
  - className: DrupipeFromProcessor
    properties:
      include_key: from

jobs:
  seed:
    type: seed
    pipeline:
      pods:
        - from: .params.pods.default
          containers:
            - from: .params.containers.common
              blocks:
                - actions:
                  - from: .params.actions.Docman.info
        - from: .params.pods.master
          containers:
            - from: .params.containers.common
              blocks:
                - actions:
                  - from: .params.actions.JobDslSeed.prepare
                  - from: .params.actions.JobDslSeed.perform

params:
  processors:
      from:
        # defines in which mode 'from' should be processed.
        mode: config
  jobs:
    __default:

  pipelines:
    default:
      name: default

  pods:
    __default:
      name: default

    master:
      name: master
      from: pods.default

    k8s:
      name: k8s
      from: pods.default

  containers:
    __default:

    common:
      image: michaeltigr/zebra-build-php-drush-docman

  pipeline:
    scripts_library:
      url: https://github.com/aroq/drupipe.git
      ref: master
      type: branch
